# Generated by Django 6.0.3 on 2026-03-13 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Қоидавайронкунӣ / Амали наҷиб')),
                ('category', models.CharField(choices=[('A', 'Гурӯҳи А: Кӯчак (-5)'), ('B', 'Гурӯҳи Б: Миёна (-15)'), ('C', 'Гурӯҳи В: Вазнин (-35)'), ('D', 'Гурӯҳи Г: Вазнин (-55)'), ('BONUS', 'Ҳавасмандкунӣ (Бонус)')], max_length=10, verbose_name='Гурӯҳ')),
                ('points_impact', models.IntegerField(verbose_name='Минус ё Плюс хол')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('grade', models.CharField(max_length=20, verbose_name='Синф (Класс)')),
                ('points', models.IntegerField(default=100, verbose_name='Холҳо (Баллы)')),
            ],
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Сана (Дата)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Шарҳ (Комментарий)')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.rule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='app.student')),
            ],
        ),
    ]
