# Generated by Django 6.0.3 on 2026-03-13 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Омӯзгор (Учитель/Админ)'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт (Логин)'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.rule', verbose_name='Қоида (Правило)'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='app.student', verbose_name='Хонанда (Ученик)'),
        ),
    ]
