# Generated by Django 6.0.3 on 2026-03-14 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_actionlog_teacher_student_user_alter_actionlog_rule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Сабти амал', 'verbose_name_plural': 'Журнали интизом'},
        ),
        migrations.AlterModelOptions(
            name='rule',
            options={'verbose_name': 'Қоида', 'verbose_name_plural': 'Қоидаҳо'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['school_class', 'last_name'], 'verbose_name': 'Хонанда', 'verbose_name_plural': 'Хонандагон'},
        ),
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.rule', verbose_name='Қоида'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='app.student', verbose_name='Хонанда'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_actions', to=settings.AUTH_USER_MODEL, verbose_name='Омӯзгор'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='category',
            field=models.CharField(choices=[('A', 'Гурӯҳи А: Кӯчак (-5)'), ('B', 'Гурӯҳи Б: Миёна (-15)'), ('C', 'Гурӯҳи В: Вазнин (-35)'), ('D', 'Гурӯҳи Г: Хеле вазнин (-55)'), ('BONUS', 'Ҳавасмандкунӣ (Бонус)')], max_length=10, verbose_name='Гурӯҳ'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='points_impact',
            field=models.IntegerField(help_text='Минус барои вайронкунӣ, Плюс барои бонус', verbose_name='Минус ё Плюс хол'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Ном (Имя)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Насаб (Фамилия)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт'),
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='Номи синф (Название класса)')),
                ('class_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_classes', to=settings.AUTH_USER_MODEL, verbose_name='Роҳбари синф')),
            ],
            options={
                'verbose_name': 'Синф',
                'verbose_name_plural': 'Синфҳо',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='app.schoolclass', verbose_name='Синф'),
        ),
    ]
