# Generated by Django 6.0.3 on 2026-03-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_actionlog_options_alter_rule_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20, unique=True, verbose_name='Соли таҳсил (Учебный год)')),
                ('is_active', models.BooleanField(default=False, verbose_name='Фаъол (Активный)')),
            ],
            options={
                'verbose_name': 'Соли таҳсил',
                'verbose_name_plural': 'Солҳои таҳсил',
                'ordering': ['-year'],
            },
        ),
    ]
