# Generated by Django 6.0.3 on 2026-03-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_teacherprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Номи фан (Предмет)')),
            ],
            options={
                'verbose_name': 'Фан',
                'verbose_name_plural': 'Фанҳо',
                'ordering': ['name'],
            },
        ),
    ]
