# Generated by Django 6.0.3 on 2026-03-14 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_teacherprofile_subjects_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Чоряк (Четверть)')),
                ('is_active', models.BooleanField(default=False, verbose_name='Фаъол (Активный)')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarters', to='app.academicyear', verbose_name='Соли таҳсил')),
            ],
            options={
                'verbose_name': 'Чоряк',
                'verbose_name_plural': 'Чорякҳо',
            },
        ),
        migrations.CreateModel(
            name='QuarterResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_points', models.IntegerField(verbose_name='Холҳои ҷамъбастӣ')),
                ('is_exemplary', models.BooleanField(default=False, verbose_name='Намунавӣ буд?')),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.quarter', verbose_name='Чоряк')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarter_results', to='app.student', verbose_name='Хонанда')),
            ],
            options={
                'verbose_name': 'Натиҷаи чоряк',
                'verbose_name_plural': 'Натиҷаҳои чоряк',
                'unique_together': {('student', 'quarter')},
            },
        ),
    ]
