# Generated by Django 5.1.6 on 2026-03-27 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_quarter_quarterresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='quarter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='app.quarter', verbose_name='Чоряк'),
        ),
        migrations.AddField(
            model_name='student',
            name='carryover_bonus',
            field=models.IntegerField(default=0, verbose_name='Бонуси гузаронидашуда'),
        ),
    ]
