# Generated by Django 5.1.6 on 2026-03-31 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_appnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='is_multiple',
            field=models.BooleanField(default=False, help_text='Можно ли применять это правило несколько раз в день', verbose_name='Многократное (Multiple)'),
        ),
    ]
