# Generated by Django 5.1.6 on 2026-03-31 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rule_is_multiple'),
    ]

    operations = [
        migrations.CreateModel(
            name='BellSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_number', models.PositiveIntegerField(unique=True, verbose_name='Номер урока')),
                ('start_time', models.TimeField(verbose_name='Начало урока')),
                ('end_time', models.TimeField(verbose_name='Конец урока')),
            ],
            options={
                'verbose_name': 'Звонок',
                'verbose_name_plural': 'Расписание звонков',
                'ordering': ['lesson_number'],
            },
        ),
    ]
