# Generated by Django 5.1.6 on 2026-03-31 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_bellschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarter',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Конец четверти'),
        ),
        migrations.AddField(
            model_name='quarter',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Начало четверти'),
        ),
    ]
