# Generated by Django 5.1.6 on 2026-04-01 04:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_quarter_end_date_quarter_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolclass',
            name='class_teacher',
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='class_teachers',
            field=models.ManyToManyField(blank=True, related_name='led_classes', to=settings.AUTH_USER_MODEL, verbose_name='Роҳбарони синф'),
        ),
    ]
