# Generated by Django 5.1.6 on 2026-04-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_message_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_edited',
            field=models.BooleanField(default=False, verbose_name='Изменено'),
        ),
        migrations.AddField(
            model_name='message',
            name='visible_to_recipient',
            field=models.BooleanField(default=True, verbose_name='Видно получателю'),
        ),
        migrations.AddField(
            model_name='message',
            name='visible_to_sender',
            field=models.BooleanField(default=True, verbose_name='Видно отправителю'),
        ),
    ]
