# Generated by Django 5.1.6 on 2026-04-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_aiconversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='chat_audio/', verbose_name='Голосовое сообщение'),
        ),
    ]
