# Generated by Django 5.1.6 on 2026-04-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_message_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/', verbose_name='Фото'),
        ),
    ]
