# Generated by Django 5.1.6 on 2026-04-10 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_fcmdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarter',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Чоряк (Четверть)'),
        ),
        migrations.AddField(
            model_name='quarter',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Чоряк (Четверть)'),
        ),
        migrations.AddField(
            model_name='quarter',
            name='name_tg',
            field=models.CharField(max_length=50, null=True, verbose_name='Чоряк (Четверть)'),
        ),
        migrations.AddField(
            model_name='rule',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Қоидавайронкунӣ / Амали наҷиб'),
        ),
        migrations.AddField(
            model_name='rule',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Қоидавайронкунӣ / Амали наҷиб'),
        ),
        migrations.AddField(
            model_name='rule',
            name='title_tg',
            field=models.CharField(max_length=255, null=True, verbose_name='Қоидавайронкунӣ / Амали наҷиб'),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Номи фан (Предмет)'),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Номи фан (Предмет)'),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_tg',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Номи фан (Предмет)'),
        ),
    ]
