# Generated by Django 5.1.6 on 2026-04-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_quarter_name_en_quarter_name_ru_quarter_name_tg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='chat_docs/', verbose_name='Документ'),
        ),
        migrations.AddField(
            model_name='message',
            name='document_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя документа'),
        ),
    ]
