# Generated by Django 5.1.6 on 2026-04-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_copy_translation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='first_name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Ном (Имя)'),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Ном (Имя)'),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name_tg',
            field=models.CharField(max_length=100, null=True, verbose_name='Ном (Имя)'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Насаб (Фамилия)'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Насаб (Фамилия)'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name_tg',
            field=models.CharField(max_length=100, null=True, verbose_name='Насаб (Фамилия)'),
        ),
    ]
