# Generated by Django 5.1.6 on 2026-04-16 14:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_student_first_name_en_student_first_name_ru_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Сана (Дата)'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Прочитано'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='category',
            field=models.CharField(choices=[('A', 'Гурӯҳи А: Кӯчак (-5)'), ('B', 'Гурӯҳи Б: Миёна (-15)'), ('C', 'Гурӯҳи В: Вазнин (-35)'), ('D', 'Гурӯҳи Г: Хеле вазнин (-55)'), ('BONUS', 'Ҳавасмандкунӣ (Бонус)')], db_index=True, max_length=10, verbose_name='Гурӯҳ'),
        ),
        migrations.AlterField(
            model_name='student',
            name='points',
            field=models.IntegerField(db_index=True, default=100, verbose_name='Холҳо (Баллы)'),
        ),
        migrations.AddIndex(
            model_name='actionlog',
            index=models.Index(fields=['student', 'quarter'], name='app_actionl_student_6783da_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'recipient'], name='app_message_sender__eb0a32_idx'),
        ),
    ]
