# Generated by Django 5.1.6 on 2026-04-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
