# Generated by Django 5.1.6 on 2026-04-20 16:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_attendancerecord_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['recipient', 'sender', 'is_read'], name='app_message_recipie_964e70_idx'),
        ),
    ]
